---
- name: Set gather_activate_ips variable
  ansible.builtin.set_fact:
    gather_activate_ips: >-
      {{ query('netbox.netbox.nb_lookup',
               'ip-addresses',
               api_endpoint=netbox_url,
               token=netbox_token,
               api_filter='tenant=%s' % (tenant_name)
         )
      }}

- name: Set variables to publish between tasks
  ansible.builtin.set_stats:
    data:
      gather_activate_ips: "{{ gather_activate_ips }}"
