---
- name: Set gather_activate_ips variable
  ansible.builtin.set_fact:
    gather_activate_ips: >-
      {{ query('netbox.netbox.nb_lookup',
               'ip-addresses',
               api_endpoint=netbox_url,
               token=netbox_token
         )
      }}
